{
 "title": "Partitions and Backlog Experiment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Schedule to start",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(task_schedule_to_start_latency_sum{namespace=\"backlog_exp\"}[10s])) by (taskqueue, task_type)/\nsum(rate(task_schedule_to_start_latency_count{namespace=\"backlog_exp\"}[10s])) by (taskqueue, task_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Matched pollers per prtn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by(taskqueue) (rate(poll_latency_count{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue!~\"(tq|temporal_sys_per_ns_tq)\", forwarded=\"false\"}[1m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(poll_latency_count{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue=\"tq\"}[1m]))  or on() vector(0) +\nsum (rate(poll_latency_count{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue!~\"temporal_sys_per_ns_tq\", forwarded=\"true\"}[1m]))  or on() vector(0)",
     "legendFormat": "tq"
    }
   ]
  },
  {
   "title": "Task dispatch rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\"}[10s])) by (task_type)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(operation) (rate(service_latency_count{operation=\"StartWorkflowExecution\", namespace=\"backlog_exp\", service_name=\"frontend\"}[10s]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "poll succeed/s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(poll_success{namespace=\"backlog_exp\", taskqueue!~\"temporal_sys.*\", task_type=\"Activity\"}[10s])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispatched tasks per partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by (taskqueue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync match rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\", source=~\"(Unspecified|History)\"}[10s]))\n/\nsum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s]))",
     "legendFormat": "history match rate"
    },
    {
     "expr": "sum(rate(poll_success_sync{namespace=~\"backlog_exp\", taskqueue=~\".*tq.*\", task_type=\"Activity\"}[10s]))\n/\nsum(rate(poll_success{namespace=~\"backlog_exp\", taskqueue=~\".*tq.*\", task_type=\"Activity\"}[10s]))",
     "legendFormat": "sync match rate"
    }
   ]
  },
  {
   "title": "Activity median dispatch latency by partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(.50, sum(rate(task_dispatch_latency_bucket{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by (le, taskqueue))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Child partition poller forward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(local_to_local_matches{namespace=~\"backlog_exp\", operation=\"PollActivityTaskQueue\",taskqueue=~\"__sys_tq_.*\"}[10s]))",
     "legendFormat": "false"
    },
    {
     "expr": "sum(rate(local_to_remote_matches{namespace=~\"backlog_exp\", operation=\"PollActivityTaskQueue\"}[10s])) + sum(rate(remote_to_remote_matches{namespace=~\"backlog_exp\", operation=\"PollActivityTaskQueue\"}[10s]))",
     "legendFormat": "true"
    }
   ]
  },
  {
   "title": "Activity average dispatch latency by partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_sum{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by (le, taskqueue)\n/\nsum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by (le, taskqueue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Child partition task forward",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\", taskqueue=~\"__sys_tq_.*\"}[10s])) by (forwarded)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "incoming pollers per prtn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "sum by(taskqueue) (rate(poll_latency_count{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue!~\"temporal_sys_per_ns_tq\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dispatched tasks per source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(rate(task_dispatch_latency_count{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by (source,forwarded,taskqueue)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Activity poll latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum(rate(poll_latency_sum{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue!~\"temporal_sys_per_ns_tq\"}[1m])) by (taskqueue, forwarded)/\nsum(rate(poll_latency_count{namespace=\"backlog_exp\", task_type=\"Activity\", taskqueue!~\"temporal_sys_per_ns_tq\"}[1m])) by (taskqueue, forwarded)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Min/Max dispatch latency by partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "expr": "label_replace(histogram_quantile(.99, sum(rate(task_dispatch_latency_bucket{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by(le, taskqueue)), \"percentile\",\"p99\", \"__name__\", \".*\")\nor\nlabel_replace(histogram_quantile(.01, sum(rate(task_dispatch_latency_bucket{namespace=~\"backlog_exp\", task_type=\"Activity\"}[10s])) by(le, taskqueue)), \"percentile\",\"p01\", \"__name__\", \".*\") ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sync/async match reported",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "targets": [
    {
     "expr": "sum(rate(syncmatch_latency_count{namespace=~\"backlog_exp\", operation=\"AddActivityTask\"}[10s])) by (taskqueue)",
     "legendFormat": "Sync {{taskqueue}}"
    },
    {
     "expr": "sum(rate(asyncmatch_latency_count{namespace=~\"backlog_exp\", operation=\"PollActivityTaskQueue\"}[10s])) by (taskqueue)",
     "legendFormat": "Async {{taskqueue}}"
    }
   ]
  },
  {
   "title": "WF median dispatch latency by partition",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "targets": [
    {
     "expr": "histogram_quantile(.50, sum(rate(task_dispatch_latency_bucket{namespace=~\"backlog_exp\", task_type=\"Workflow\"}[10s])) by (le, taskqueue, source))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "targets": [
    {
     "expr": "sum(rate(service_error_with_type[10s])) by (error_type)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}